Repository bwillett2003/rancid-tomatillos, pull requests merged in 2024-12, with the labels that each got.

#21 Added CSS to MovieDetails and home button, refactored css for title.
  src/App/App.css
  src/App/App.js
  src/MovieDetails/MovieDetails.css
  src/MovieDetails/MovieDetails.js
  src/MoviePoster/MoviePoster.css
Labels: Iteration 3

#24 Refactored upVote/downVote to use real endpoints.
  src/App/App.js
Labels: Iteration 4

#25 Cypress testing for movie details and creation of fixture file.
  cypress/e2e/movie_details_spec.cy.js
  cypress/fixtures/movies/155.json
Labels: Iteration 5

#28 upvote and downvote tests work
  cypress/e2e/movie_container.cy.js
Labels: Iteration 5
